services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
  db:
    image: postgres:latest
    container_name: urlshortener-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url_shortener
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d url_shortener"]
      interval: 1s
      timeout: 5s
      retries: 10
  redis:
    image: "redis:alpine"
    ports:
      - ":6379"

  celery:
    build:
      context: .
    environment:
      FLASK_APP: app
    volumes:
      - .:/app
    command: celery -A tools.celery worker --loglevel=info
    depends_on:
      - redis
      - db
  test:
    build: .
    command: [ "pytest", "tests/" ]  # Command to run tests
    volumes:
      - .:/app